### PR TITLE
Added Polyline convertion to MKPolyline + tests

### PR DESCRIPTION
**Pull request by orxelm**

### CODE REVIEW

**Comment by orxelm** [comment]
@raphaelmor @tomtaylor can i get some attention here 😃

**Comment by joeblau** [comment]
Lets land this little gem right here 🛬

**Comment by raphaelmor** [comment]
Great PR ! 
Could you update the README file and move the "Convert to MKPolyline" to Features ?

Thanks !

**Comment by orxelm** [comment]
Sure 👍

**Comment by tomtaylor** [comment]
Looks good to me - let's get this merged when Travis finds the time to run the tests.

**Comment by 1ec5** [comment]
This change broke tvOS and watchOS builds: #40.

**Pull request merged**
