### PR TITLE
[Hold] Migrate to Swift 3

### PR DESCRIPTION
**Pull request by 1ec5**
Ran the Swift 3 migrator on the Polyline and PolylineTests targets. Replaced two resulting placeholder tokens with the correct expressions.

I’d like to massage [this line](https://github.com/1ec5/Polyline/blob/bb896be3d8393c90b1e490a03aa307636faa3253/Polyline/Polyline.swift#L160) a bit, perhaps with `Data.enumerateBytes(_:)` or `Data.withUnsafeBytes(_:)`, but I’m not sure how to work that in.

Hold until Xcode 8 is released.

/cc @tmcw

### CODE REVIEW

**Comment by superpeteblaze** [comment]
@1ec5 Just wondering if you are planning on moving this forward. If not, I can open a separate PR. Just curious as I use mapbox directions in a live app and want to be ready for Swift 3.

**Comment by 1ec5** [comment]
Thanks for the reminder. Feel free to open a separate PR; this one is a bit stale since it was written for an earlier beta of Xcode 8. (@tomtaylor is managing this repo these days.)

**Comment by superpeteblaze** [comment]
Sure @1ec5, no problem. I will open a separate PR.

**Comment by superpeteblaze** [comment]
Hi @tomtaylor, I would like to help with migration to swift 3. Could you possibly add me as a collaborator with write access?

**Comment by superpeteblaze** [comment]
@1ec5, I have forked Polyline and have a Swift 3 branch which seems to work fine

**Comment by DanTug** [comment]
How is the migration to swift 3 coming? I would really love a version with it.

Thanks.

**Comment by tomtaylor** [comment]
@superpeteblaze @DanTug: if anyone can get me a PR with a Swift 3.0 build that passes CI, I'll merge and release it.

Does anyone know what the right approach is to support projects that use Swift 2.3? The two aren't interoperable in the same project are they? Should we maintain a 3.x release for Swift 2.3 and ship 4.0 as a Swift 3.0 release?

**Comment by superpeteblaze** [comment]
@DanTug I forked Polyline and migrated to Swift 3. See [here](https://github.com/superpeteblaze/Polyline).

**Comment by superpeteblaze** [comment]
Hi @tomtaylor. I think the right approach for 2.3 & 3.0 is to first merge 2.3 and tag it as a release. Then do the same for 3.0. I will have a look at getting the Swift 3 branch to pass CI when I get a chance.

**Comment by tomtaylor** [comment]
@superpeteblaze yep - 2.3 was shipped in 3.3.0.

**Comment by superpeteblaze** [comment]
Ok cool @tomtaylor. If we can get a Swift 3 branch passing CI then we can ship that as 4.0 as you suggest.

**Comment by DanTug** [comment]
Thanks. I'll have a look at the forked version.

**Comment by tomtaylor** [comment]
Alright, that's all merged onto master and released as 4.0.0. Happy Polylining!

**Comment by superpeteblaze** [comment]
Thanks @tomtaylor, I'll switch from using my fork to using this

**Pull request closed without merging**
