### PR TITLE
Set SWIFT_VERSION in the podspec

### PR DESCRIPTION
**Pull request by frederoni**

### CODE REVIEW

**Comment by tomtaylor** [comment]
My understanding is that Cocoapods 1.1.0, will detect based on the `.swift-version` file. Can you explain more about why this is required?

**Comment by frederoni** [comment]
@tomtaylor I think .swift-version is interpreted when you run the program via CLI or swiftenv for example. It doesn't seem like it's the purpose of CocoaPods/CocoaPods#5540
Also, Cocoapods 1.1.0 is not yet released.

**Comment by superpeteblaze** [comment]
@tomtaylor @frederoni I wrote this recently when updating one of my pods - https://medium.com/@superpeteblaze/swift-3-cocoapods-ccb72e0de750#.lzth4e9s2

**Comment by frederoni** [comment]
Thanks @superpeteblaze 
Indeed it works with rc.2 but the fix in this PR works with the latest stable release of cocoapods.
@tomtaylor you can go ahead and delete this PR unless you want to support older versions of cocoapods.

**Comment by tomtaylor** [comment]
@frederoni thanks, I think there's probably other Xcode 8 stuff that Cocoapods 1.1.0 will/does support, so it's not unreasonable to expect people to update. I'll close this.

**Pull request closed without merging**
